import {useMemo,useState,type ComponentType} from 'react';
import {Activity,ArrowUpRight,CalendarDays,ChartNoAxesCombined,Clock3,Download,Globe2,Monitor,Play,RefreshCw,Server,Smartphone,Tablet,TrendingUp,Users,Video} from 'lucide-react';
type Range='24h'|'7d'|'30d'|'90d'; const ranges:Range[]=['24h','7d','30d','90d'];
const points=[38,45,42,57,51,66,62,73,68,82,77,91,86,96,88,104,98,112,108,121,116,128,124,136];
const popular=[['One Piece',18420,18],['Solo Leveling',15210,15],['Jujutsu Kaisen',12840,13],['Demon Slayer',10490,10],['Attack on Titan',9270,9]];
const providers=[['AniWave',72,1.8],['MegaCloud',64,2.3],['Vidstream',51,3.1],['StreamWish',43,4.2]];
const devices:Array<[string,number,ComponentType<{size?:number}>]>=[['Desktop',58,Monitor],['Mobile',31,Smartphone],['Tablet',11,Tablet]];
function Metric({icon:Icon,label,value,change,sub}:{icon:any;label:string;value:string;change:string;sub:string}){return <article className="an-metric"><div className="an-metric-top"><span className="an-icon"><Icon size={16}/></span><small>{label}</small><span className="an-change"><ArrowUpRight size={11}/>{change}</span></div><strong>{value}</strong><p>{sub}</p></article>}
export function AnalyticsPage(){
 const [range,setRange]=useState<Range>('7d'); const [tab,setTab]=useState<'traffic'|'providers'>('traffic'); const [refreshing,setRefreshing]=useState(false);
 const max=Math.max(...points); const pointX=(i:number)=>`${(i/(spark.length-1))*100}%`; const pointY=(p:number)=>`${100-(p/max)*78}%`; const svgPoint=(p:number,i:number)=>`${(i/(spark.length-1))*1000},${300-(p/max)*234}`; const areaClip=`polygon(${spark.map((p,i)=>`${pointX(i)} ${pointY(p)}`).join(',')},100% 100%,0 100%)`; const scale=range==='24h'?1:range==='7d'?1.8:range==='30d'?3.6:6.4;
 const totalViews=Math.round(68240*scale).toLocaleString(),streamStarts=Math.round(38920*scale).toLocaleString(),visitors=Math.round(24810*scale).toLocaleString(),users=Math.round(8340*scale).toLocaleString();
 const spark=useMemo(()=>points.map(v=>v*(range==='24h'?1:range==='7d'?1:range==='30d'?1.35:1.7)),[range]);
 const refresh=()=>{setRefreshing(true);setTimeout(()=>setRefreshing(false),650)};
 return <section className="analytics-page">
  <div className="an-hero"><div><div className="an-kicker"><ChartNoAxesCombined size={13}/> PLATFORM INSIGHTS</div><h1>Analytics</h1><p>Understand traffic, viewing activity, and streaming performance across AniFuze.</p></div><div className="an-actions"><button className="an-btn ghost" onClick={refresh}><RefreshCw className={refreshing?'an-spin':''} size={14}/>Refresh</button><button className="an-btn"><Download size={14}/>Export report</button></div></div>
  <div className="an-range">{ranges.map(r=><button className={range===r?'active':''} key={r} onClick={()=>setRange(r)}>{r}</button>)}<span><CalendarDays size={13}/> Current demo period</span></div>
  <div className="an-grid"><Metric icon={Users} label="Visitors" value={visitors} change="+12.8%" sub="vs previous period"/><Metric icon={Activity} label="Registered users" value={users} change="+8.4%" sub="active accounts"/><Metric icon={Video} label="Anime views" value={totalViews} change="+16.2%" sub="catalog page views"/><Metric icon={Play} label="Stream starts" value={streamStarts} change="+10.7%" sub="playback sessions"/></div>
  <div className="an-main-grid">
   <article className="an-card an-chart-card"><div className="an-card-head"><div><h2>Traffic overview</h2><p>Views and stream activity over the selected period.</p></div><div className="an-legend"><i/>Views <i/>Streams</div></div>
    <div className="an-chart"><div className="an-y"><span>150</span><span>100</span><span>50</span><span>0</span></div><div className="an-plot">{[0,1,2,3].map(i=><div className="an-gridline" style={{bottom:`${i*33.33}%`}} key={i}/>)}<div className="an-area" style={{clipPath:areaClip}}/><svg viewBox="0 0 1000 300" preserveAspectRatio="none"><polyline points={spark.map(svgPoint).join(' ')} fill="none" stroke="currentColor" strokeWidth="4" vectorEffect="non-scaling-stroke"/></svg>{spark.map((p,i)=><span className="an-point" key={i} style={{left:`${(i/(spark.length-1))*100}%`,bottom:`${(p/max)*78}%`}}/>)}</div></div>
    <div className="an-x">{['00:00','04:00','08:00','12:00','16:00','20:00','Now'].map(x=><span key={x}>{x}</span>)}</div>
   </article>
   <article className="an-card"><div className="an-card-head"><div><h2>Peak activity</h2><p>When your audience is most active.</p></div><Clock3 size={16}/></div><div className="an-peak"><strong>20:00 – 22:00</strong><span>Peak viewing window</span><div className="an-bars">{[35,42,48,56,64,78,91,84,69,52,39,30].map((x,i)=><i style={{height:`${x}%`}} key={i}/>)}</div><div className="an-peak-labels"><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></div></div></article>
  </div>
  <div className="an-main-grid">
   <article className="an-card"><div className="an-card-head"><div><h2>Popular anime</h2><p>Most viewed titles in the selected period.</p></div><TrendingUp size={16}/></div><div className="an-table">{popular.map(([name,views,share],i)=><div className="an-row" key={name}><b className="an-rank">{String(i+1).padStart(2,'0')}</b><div className="an-title"><strong>{name}</strong><span>{share}% of total views · {Number(views).toLocaleString()} views</span></div><div className="an-progress"><i style={{width:`${share*4.8}%`}}/></div>)}</div></article>
   <article className="an-card"><div className="an-card-head"><div><h2>Audience devices</h2><p>Sessions by device category.</p></div><Globe2 size={16}/></div><div className="an-devices">{devices.map(([name,p,Icon])=><div key={name}><span className="an-device-icon"><Icon size={15}/></span><div><b>{name}</b><small>{p}% of sessions</small></div><strong>{p}%</strong></div>)}</div><div className="an-device-total"><span>Browser coverage</span><b>Chrome 62% · Safari 24% · Firefox 9%</b></div></article>
  </div>
  <article className="an-card an-provider-card"><div className="an-card-head"><div><h2>Provider performance</h2><p>Streaming provider usage and response time.</p></div><div className="an-segment"><button className={tab==='traffic'?'active':''} onClick={()=>setTab('traffic')}>Usage</button><button className={tab==='providers'?'active':''} onClick={()=>setTab('providers')}>Response</button></div></div><div className="an-provider-list">{providers.map(([name,use,lat])=><div className="an-provider" key={name}><span className="an-provider-icon"><Server size={14}/></span><div><strong>{name}</strong><small>{tab==='traffic'?`${use}% of stream starts`:`${lat}s average response`}</small></div><div className="an-provider-meter"><i style={{width:`${use}%`}}/></div>)}</div></article>
  <div className="an-footnote"><span>Demo analytics data</span><span>Backend collection will replace these values in the analytics backend phase.</span></div>
 </section>
}