import {useEffect,useState} from 'react';
import {Button,Card} from '../../components/ui';
import {useApp} from '../../contexts/AppContext';

function CommentsPage(){
 const{toast}=useApp();const[items,setItems]=useState<any[]>([]);const[status,setStatus]=useState('');const[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const p=status?'?status='+status:'';const r=await fetch('/api/admin/comments'+p);const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load comments');setItems(d.comments||[])}catch(e:any){toast(e.message,'error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[status]);
 const patch=async(id:string,body:any)=>{const r=await fetch('/api/admin/comments/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return toast(d.error||'Update failed','error');setItems(x=>x.map(v=>v.id===id?d.comment:v));toast('Comment updated')};
 const remove=async(id:string)=>{if(!confirm('Delete this comment?'))return;const r=await fetch('/api/admin/comments/'+id,{method:'DELETE'});const d=await r.json();if(!r.ok)return toast(d.error||'Delete failed','error');setItems(x=>x.filter(v=>v.id!==id));toast('Comment deleted')};
 return <section className="form-page"><div className="page-heading"><div><h1>Comments</h1><p>Moderate community comments and control visibility and pinned status.</p></div><Button onClick={load}>Refresh</Button></div><Card title="Comment moderation"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="visible">Visible</option><option value="hidden">Hidden</option><option value="deleted">Deleted</option></select></label>{loading?<p>Loading…</p>:<div className="table-wrap"><table><thead><tr><th>User</th><th>Comment</th><th>Status</th><th>Pinned</th><th>Created</th><th>Actions</th></tr></thead><tbody>{items.map(v=><tr key={v.id}><td>{v.username||v.user_id}</td><td>{v.body}</td><td><select value={v.status} onChange={e=>patch(v.id,{status:e.target.value})}><option value="visible">Visible</option><option value="hidden">Hidden</option><option value="deleted">Deleted</option></select></td><td><input type="checkbox" checked={!!v.pinned} onChange={e=>patch(v.id,{pinned:e.target.checked})}/></td><td>{new Date(v.created_at).toLocaleString()}</td><td><Button onClick={()=>remove(v.id)}>Delete</Button></td></tr>)}</tbody></table></div>}</Card></section>
}
function ReportsPage(){
 const{toast}=useApp();const[items,setItems]=useState<any[]>([]);const[status,setStatus]=useState('');const[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/reports'+(status?'?status='+status:''));const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load reports');setItems(d.reports||[])}catch(e:any){toast(e.message,'error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[status]);
 const patch=async(id:string,next:string)=>{const r=await fetch('/api/admin/reports/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next})});const d=await r.json();if(!r.ok)return toast(d.error||'Update failed','error');setItems(x=>x.map(v=>v.id===id?d.report:v));toast('Report updated')};
 return <section className="form-page"><div className="page-heading"><div><h1>Reports</h1><p>Review user reports and record their resolution status.</p></div><Button onClick={load}>Refresh</Button></div><Card title="Reports queue"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="pending">Pending</option><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></label>{loading?<p>Loading…</p>:<div className="table-wrap"><table><thead><tr><th>Target</th><th>Reason</th><th>Reporter</th><th>Status</th><th>Created</th></tr></thead><tbody>{items.map(v=><tr key={v.id}><td>{v.target_type}: {v.target_id}</td><td>{v.reason}</td><td>{v.reporter_username||'Anonymous'}</td><td><select value={v.status} onChange={e=>patch(v.id,e.target.value)}><option value="pending">Pending</option><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></td><td>{new Date(v.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</Card></section>
}
export {CommentsPage,ReportsPage};