import {useEffect,useState} from 'react';
import {Button,Card,EmptyState,Badge} from '../../components/ui';

type Notice={id:string;title:string;message:string;type:string;audience:string;scheduled_at?:string|null;sent_at?:string|null;enabled:boolean;created_at:string};
const DEMO_KEY='anifuze_demo_notifications_admin';
const isDemo=()=>window.location.hostname.endsWith('github.io');
const readDemo=():Notice[]=>{try{const value=JSON.parse(localStorage.getItem(DEMO_KEY)||'[]');return Array.isArray(value)?value:[]}catch{return []}};
const writeDemo=(items:Notice[])=>localStorage.setItem(DEMO_KEY,JSON.stringify(items));

export function NotificationsAdminPage(){
 const[items,setItems]=useState<Notice[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[form,setForm]=useState({title:'',message:'',type:'release',audience:'all',scheduled_at:'',enabled:true});
 const load=async()=>{setLoading(true);try{if(isDemo()){setItems(readDemo());return}const r=await fetch('/api/admin/notifications');const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load notifications');setItems(d.notifications||[])}catch(e:any){alert(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const create=async()=>{setBusy(true);try{if(isDemo()){const n={id:crypto.randomUUID(),...form,scheduled_at:form.scheduled_at||null,created_at:new Date().toISOString()};const next=[n,...readDemo()];writeDemo(next);setItems(next);setForm({title:'',message:'',type:'release',audience:'all',scheduled_at:'',enabled:true});return}const r=await fetch('/api/admin/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,scheduled_at:form.scheduled_at||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create notification');setItems(x=>[d.notification,...x]);setForm({title:'',message:'',type:'release',audience:'all',scheduled_at:'',enabled:true})}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 const deliver=async(n:Notice)=>{setBusy(true);try{if(isDemo()){const next=items.map(i=>i.id===n.id?{...i,sent_at:new Date().toISOString(),scheduled_at:null}:i);writeDemo(next);setItems(next);return}const r=await fetch('/api/admin/notifications/'+n.id+'/deliver',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not deliver notification');setItems(x=>x.map(i=>i.id===n.id?{...i,sent_at:new Date().toISOString()}:i));}catch(e:any){alert(e.message)}finally{setBusy(false)}};\n const toggle=async(n:Notice)=>{if(isDemo()){const next=items.map(i=>i.id===n.id?{...i,enabled:!i.enabled}:i);writeDemo(next);setItems(next);return}const r=await fetch('/api/admin/notifications/'+n.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!n.enabled})});const d=await r.json();if(r.ok)setItems(x=>x.map(i=>i.id===n.id?d.notification:i))};
 const remove=async(n:Notice)=>{if(!confirm('Delete this notification?'))return;if(isDemo()){const next=items.filter(i=>i.id!==n.id);writeDemo(next);setItems(next);return}const r=await fetch('/api/admin/notifications/'+n.id,{method:'DELETE'});if(r.ok)setItems(x=>x.filter(i=>i.id!==n.id))};
 return <section className="form-page"><div className="page-heading"><p>Publish release alerts, system updates, and audience notifications.</p><Button variant="ghost" onClick={load} disabled={loading}>Refresh</Button></div>
 <Card title="Create notification"><div className="form-grid"><label>Title<input maxLength={255} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="release">Release</option><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="system">System</option></select></label><label>Audience<select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="all">All users</option><option value="users">Users</option><option value="admins">Admins</option></select></label><label>Schedule<input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><label className="wide">Message<textarea maxLength={5000} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label></div><Button onClick={create} disabled={busy||!form.title.trim()||!form.message.trim()}>{busy?'Publishing…':'Create notification'}</Button></Card>
 <Card title={loading?'Loading notifications…':String(items.length)+' notifications'}>{!loading&&!items.length?<EmptyState title="No notifications yet."/>:<div className="notification-admin-list">{items.map(n=><div className="notification-admin-row" key={n.id}><div><strong>{n.title}</strong><p>{n.message}</p><small>{n.type} · {n.audience} · {n.scheduled_at?'Scheduled':'Immediate'}{n.sent_at?' · Sent '+new Date(n.sent_at).toLocaleString():''}</small></div><Badge>{n.sent_at?'Sent':n.enabled?'Enabled':'Disabled'}</Badge>{n.enabled&&!n.sent_at&&<button className="link-button" onClick={()=>deliver(n)} disabled={busy}>Send now</button>}<button className="link-button" onClick={()=>toggle(n)} disabled={busy}>{n.enabled?'Disable':'Enable'}</button><button className="link-button" onClick={()=>remove(n)} disabled={busy}>Delete</button></div>)}</div>}</Card>
 </section>;
}
