import {useEffect,useState} from 'react';
type Ticket={id:string;subject:string;message:string;status:string;priority:string;external_id?:string;created_at:string};
export function SupportPage(){const[tickets,setTickets]=useState<Ticket[]>([]);const[subject,setSubject]=useState('');const[message,setMessage]=useState('');const[priority,setPriority]=useState('normal');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[ok,setOk]=useState('');
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/support');const j=await r.json();if(!r.ok)throw Error(j.error);setTickets(j.tickets)}catch(e){setError(e instanceof Error?e.message:'Failed to load support')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const create=async()=>{setBusy(true);setError('');setOk('');try{const r=await fetch('/api/admin/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,message,priority})});const j=await r.json();if(!r.ok)throw Error(j.error);setTickets(t=>[j.ticket,...t]);setSubject('');setMessage('');setOk('Support ticket submitted.')}catch(e){setError(e instanceof Error?e.message:'Failed to submit ticket')}finally{setBusy(false)}};
 const update=async(id,status)=>{try{const r=await fetch('/api/admin/support/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const j=await r.json();if(!r.ok)throw Error(j.error);setTickets(t=>t.map(x=>x.id===id?j.ticket:x))}catch(e){setError(e instanceof Error?e.message:'Failed to update ticket')}};
 return <div className="system-info-page support-page admin-page"><div className="page-heading"><div><span className="system-kicker">HELP & SUPPORT</span><h2>Support</h2><p>Contact the AniFuze support team and track installation issues from one place.</p></div><button className="btn-secondary" onClick={load}>Refresh</button></div>{error&&<div className="admin-alert error">{error}</div>}{ok&&<div className="maintenance-success">{ok}</div>}
 <div className="support-grid"><section className="admin-panel"><div className="panel-heading"><div><h3>Open a support ticket</h3><p>Useful installation diagnostics are attached automatically when configured.</p></div></div><label className="maintenance-field"><span>Subject</span><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Describe the issue"/></label><label className="maintenance-field"><span>Priority</span><select value={priority} onChange={e=>setPriority(e.target.value)}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></label><label className="maintenance-field"><span>Message</span><textarea rows={7} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Tell us what happened..."/></label><button className="btn-primary" onClick={create} disabled={busy||!subject.trim()||!message.trim()}>{busy?'Submitting…':'Submit ticket'}</button></section>
 <section className="admin-panel"><div className="panel-heading"><div><h3>Support connection</h3><p>Connect your support platform with a webhook.</p></div></div><div className="support-info"><strong>Webhook integration</strong><span>Set <code>ANIFUZE_SUPPORT_WEBHOOK_URL</code> on the server. New tickets are POSTed with installation ID, domain, version and ticket data.</span><strong>Privacy</strong><span>Only the information needed for support is transmitted. The webhook is optional.</span></div></section></div>
 <section className="admin-panel support-tickets"><div className="panel-heading"><div><h3>Ticket history</h3><p>{tickets.length} ticket{tickets.length===1?'':'s'}</p></div></div>{loading?<div className="system-checks">Loading…</div>:tickets.length===0?<div className="empty-state">No support tickets yet.</div>:<div className="support-list">{tickets.map(t=><article key={t.id} className="support-ticket"><div className="support-ticket-head"><div><strong>{t.subject}</strong><small>{new Date(t.created_at).toLocaleString()}</small></div><span className={'license-badge '+t.status}>{t.status}</span></div><p>{t.message}</p><div className="support-ticket-foot"><span>Priority: {t.priority}</span><select value={t.status} onChange={e=>update(t.id,e.target.value)}><option>open</option><option>pending</option><option>resolved</option><option>closed</option></select></div></article>)}</div>}</section></div>}
