import crypto from 'node:crypto';
import {query} from '../db/index.js';
import {getProvider,decryptProviderCredential} from './providers.js';

const METHODS=new Set(['GET','POST','PUT','PATCH','DELETE']);
function parseObject(value,name){if(value==null||value==='')return {};if(typeof value==='object'&&!Array.isArray(value))return value;try{const parsed=JSON.parse(String(value));if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();return parsed}catch{throw new Error(name+' must be valid JSON object.');}}
function parseHeaders(value){const obj=parseObject(value,'headers');const out={};for(const [k,v] of Object.entries(obj)){if(!/^[A-Za-z0-9!#$%&'*+.^_|~-]+$/.test(k)||typeof v!=='string')throw new Error('Invalid header.');if(/^(host|content-length|connection|transfer-encoding)$/i.test(k))continue;out[k]=v.slice(0,4000)}return out}
function safeUrl(base,endpoint){const b=new URL(base);if(!['http:','https:'].includes(b.protocol))throw new Error('Provider URL must use HTTP or HTTPS.');const e=new URL(String(endpoint||''),b);if(e.origin!==b.origin)throw new Error('Console endpoint must stay on the provider origin.');return e}
function credentialsAsHeaders(cipher){const raw=decryptProviderCredential(cipher);if(!raw)return {};try{const obj=JSON.parse(raw);const headers={};if(typeof obj.apiKey==='string')headers['X-Api-Key']=obj.apiKey;if(typeof obj.api_key==='string')headers['X-Api-Key']=obj.api_key;if(typeof obj.token==='string')headers.Authorization='Bearer '+obj.token;return headers}catch{return {}}}
export async function executeProviderRequest({providerId,method='GET',endpoint='/',headers={},queryParams={},body}={}){
 const p=await getProvider(providerId);if(!p)throw new Error('Provider not found.');if(!p.enabled)throw new Error('Provider is disabled.');method=String(method).toUpperCase();if(!METHODS.has(method))throw new Error('Unsupported HTTP method.');const url=safeUrl(p.base_url,endpoint);for(const [k,v] of Object.entries(parseObject(queryParams,'query'))){if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')url.searchParams.set(k,String(v));}
 const h={...credentialsAsHeaders(p.credentials_encrypted),...parseHeaders(headers),'Accept':'application/json'};let payload;if(!['GET','DELETE'].includes(method)&&body!==undefined&&body!==''){payload=typeof body==='string'?body:JSON.stringify(body);if(!Object.keys(h).some(k=>k.toLowerCase()==='content-type'))h['Content-Type']='application/json';}
 const started=Date.now();let response;let responseText='';try{const ac=new AbortController();const timer=setTimeout(()=>ac.abort(),15000);response=await fetch(url,{method,headers:h,body:payload,redirect:'manual',signal:ac.signal});clearTimeout(timer);responseText=(await response.text()).slice(0,100000)}catch(e){throw new Error(e.name==='AbortError'?'Provider request timed out':e.message)}
 const elapsed=Date.now()-started;const responseHeaders={};response.headers.forEach((v,k)=>{responseHeaders[k]=v});const id=crypto.randomUUID();const inputHeaders=parseHeaders(headers);const redactedHeaders={};for(const [k,v] of Object.entries(inputHeaders))redactedHeaders[k]=/authorization|api[-_]?key|token|cookie/i.test(k)?'[REDACTED]':v;
 await query('INSERT INTO af_provider_request_history(id,provider_id,method,endpoint,request_headers,request_query,request_body,response_status,response_time_ms,response_headers,response_body,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,CURRENT_TIMESTAMP)',[id,String(providerId),method,String(endpoint||'/'),JSON.stringify(redactedHeaders),JSON.stringify(Object.fromEntries(url.searchParams)),payload?.slice(0,100000)||null,response.status,elapsed,JSON.stringify(responseHeaders),responseText]);
 return {id,method,endpoint:String(endpoint||'/'),status:response.status,statusText:response.statusText,time_ms:elapsed,headers:responseHeaders,body:responseText};
}
export async function listProviderHistory(providerId,limit=50){const n=Math.min(100,Math.max(1,Number(limit)||50));const r=await query('SELECT id,provider_id,method,endpoint,request_headers,request_query,request_body,response_status,response_time_ms,response_headers,response_body,created_at FROM af_provider_request_history WHERE provider_id=$1 ORDER BY created_at DESC LIMIT '+n,[String(providerId)]);return r.rows}
export async function clearProviderHistory(providerId){await query('DELETE FROM af_provider_request_history WHERE provider_id=$1',[String(providerId)])}
export async function getProviderHistory(id){const r=await query('SELECT * FROM af_provider_request_history WHERE id=$1',[String(id)]);return r.rows[0]||null}
