import {useEffect,useState} from 'react';
import {Card,StatCard,Badge} from '../../components/ui';
const Table=({heads,rows}:{heads:string[];rows:any[][]})=><div className="table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>;
export function PlatformDashboard(){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;fetch('/api/admin/platform/overview').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load platform overview.');return d}).then(d=>{if(active)setData(d.overview)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Could not load platform overview.')});return()=>{active=false}},[]);
 if(error)return <Card title="Platform overview"><p>{error}</p></Card>;
 if(!data)return <Card title="Platform overview"><p>Loading platform metrics…</p></Card>;
 return <><div className="stats"><StatCard name="Customers" value={String(data.customers.total)}/><StatCard name="Anime" value={String(data.anime.total)}/><StatCard name="Episodes" value={String(data.episodes.total)}/><StatCard name="Providers" value={String(data.providers.total)}/></div><div className="stats"><StatCard name="Templates" value={String(data.templates.total)}/><StatCard name="Comments" value={String(data.comments.total)}/><StatCard name="Pending reports" value={String(data.reports.pending)}/><StatCard name="Analytics events" value={String(data.analytics.total)}/></div><Card title="Platform health"><div className="healthrows"><div><b>Active customers</b><span>{data.customers.active}</span></div><div><b>Enabled anime</b><span>{data.anime.active}</span></div><div><b>Visible episodes</b><span>{data.episodes.visible}</span></div><div><b>Enabled providers</b><span>{data.providers.active}</span></div><div><b>Active templates</b><span>{data.templates.active}</span></div><div><b>Audit records</b><span>{data.audit.total}</span></div></div></Card></>}
export function PlatformTable({kind}:{kind:string}){const heads:any={customers:['Customer','Site','Status','Plan','Created','Last active'],templates:['Template','Creator','Status','Price','Installs','Rating'],creators:['Creator','Templates','Status','Joined'],orders:['Order ID','Customer','Template','Amount','Status','Date'],reviews:['Customer','Template','Rating','Content','Status'],reports:['Reporter','Target','Reason','Status'],settings:['Marketplace','Moderation','Platform branding','System settings']} ;const h=heads[kind]||['Setting','Value','Status'];return <Card title={`Platform ${kind}`}><Table heads={h} rows={Array.from({length:5},(_,i)=>h.map((x:string)=>x==='Status'?<Badge>{i?'Active':'Pending'}</Badge>:`${x} ${i+1}`))}/></Card>}
