import {Router} from 'express';
import {requireAdmin} from './auth.js';
import {requirePermission} from '../auth/permissions.js';
import {listTemplates,getTemplate,installTemplate,listInstalledTemplates,getActiveTemplate,activateTemplate} from '../services/templates.js';
const router=Router();
router.get('/template',async(_req,res)=>{try{res.json({ok:true,template:await getActiveTemplate()});}catch(e){res.status(500).json({ok:false,error:e.message});}});
router.get('/admin/templates/marketplace',requireAdmin,requirePermission('templates_view'),async(_req,res)=>{try{res.json({ok:true,templates:await listTemplates()});}catch(e){res.status(503).json({ok:false,error:e.message});}});
router.get('/admin/templates',requireAdmin,requirePermission('templates_view'),async(_req,res)=>{try{res.json({ok:true,templates:await listInstalledTemplates()});}catch(e){res.status(500).json({ok:false,error:e.message});}});
router.get('/admin/templates/:id',requireAdmin,requirePermission('templates_view'),async(req,res)=>{try{const t=await getTemplate(req.params.id);res.json({ok:true,template:t});}catch(e){res.status(404).json({ok:false,error:e.message});}});
router.post('/admin/templates/:id/install',requireAdmin,requirePermission('templates_manage'),async(req,res)=>{try{res.status(201).json({ok:true,template:await installTemplate(req.params.id)});}catch(e){res.status(400).json({ok:false,error:e.message});}});
router.patch('/admin/templates/active',requireAdmin,requirePermission('templates_manage'),async(req,res)=>{try{res.json({ok:true,template:await activateTemplate(req.body?.id)});}catch(e){res.status(400).json({ok:false,error:e.message});}});
export {router as templateRouter};