import {Router} from 'express';
import {createUser,loginUser,getUserFromRequest,logoutUser,userCookie,clearUserCookie} from '../services/userAuth.js';
const router=Router(),attempts=new Map();
const allow=(key,max=8,windowMs=15*60*1000)=>{const now=Date.now(),x=attempts.get(key);if(!x||now-x.start>windowMs){attempts.set(key,{start:now,count:1});return true}x.count++;return x.count<=max};
const setSession=(res,session)=>userCookie(res,session.id,session.remember?60*60*24*30:60*60*24);
router.post('/user/register',async(req,res)=>{if(!allow('register:'+req.ip,6))return res.status(429).json({ok:false,error:'Too many attempts. Try again later.'});try{const user=await createUser(req.body||{});const session=await loginUser({email:req.body?.email,password:req.body?.password,req,remember:req.body?.remember!==false});setSession(res,session);res.status(201).json({ok:true,user:session.user})}catch(e){res.status(400).json({ok:false,error:e.message})}});
router.post('/user/login',async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();if(!allow('login:'+req.ip+':'+email))return res.status(429).json({ok:false,error:'Too many login attempts. Try again later.'});try{const session=await loginUser({email,password:req.body?.password,req,remember:req.body?.remember!==false});setSession(res,session);res.json({ok:true,user:session.user})}catch(e){res.status(401).json({ok:false,error:e.message})}});
router.get('/user/me',async(req,res)=>{const user=await getUserFromRequest(req);if(!user)return res.status(401).json({ok:false,error:'Not authenticated.'});res.json({ok:true,user})});
router.post('/user/logout',async(req,res)=>{await logoutUser(req);clearUserCookie(res);res.json({ok:true})});
export {router as userAuthRouter};
