import express from 'express';
import {config} from './config.js';
import {healthCheck} from './db/index.js';
import {runMigrations} from './migrate.js';
import {installerRouter} from './routes/installer.js';
import {authRouter} from './routes/auth.js';
import {userAuthRouter} from './routes/userAuth.js';
import {anilistRouter} from './routes/anilist.js';
import {episodesRouter} from './routes/episodes.js';
import {providersRouter} from './routes/providers.js';
import {providerConsoleRouter} from './routes/providerConsole.js';
import {providerHealthRouter} from './routes/providerHealth.js';
import {publicCatalogRouter} from './routes/publicCatalog.js';
import {homepageRouter} from './routes/homepage.js';
import {templateRouter} from './routes/templates.js';
import {siteBuilderRouter} from './routes/siteBuilder.js';
import {appearanceRouter} from './routes/appearance.js';
import {appearanceUploadRouter} from './routes/appearanceUpload.js';
import {navigationRouter} from './routes/navigation.js';
import {footerRouter} from './routes/footer.js';
import {pagesRouter} from './routes/pages.js';
import {seoRouter} from './routes/seo.js';
import {usersRouter} from './routes/users.js';
import {communityRouter} from './routes/community.js';
import {notificationsRouter} from './routes/notifications.js';
import {emailRouter} from './routes/email.js';
import {auditRouter} from './routes/audit.js';
import {backupsRouter} from './routes/backups.js';
import {systemInfoRouter} from './routes/systemInfo.js';
import {cacheRouter} from './routes/cache.js';
import {maintenanceRouter} from './routes/maintenance.js';
import {updatesRouter} from './routes/updates.js';
import {licenseRouter} from './routes/license.js';
import {supportRouter} from './routes/support.js';
import {oauthRouter} from './routes/oauth.js';
import {maintenanceGate} from './services/maintenance.js';
import {processDueNotifications} from './services/notifications.js';
import {isInstallerLocked} from './installer/index.js';

const app=express();
app.disable('x-powered-by');
app.use(express.json({limit:'100mb'}));
app.use('/uploads',express.static('storage/uploads',{fallthrough:false,maxAge:'1h',index:false}));

app.get('/api/health',async(_req,res)=>{try{res.json({ok:true,service:'anifuze',database:await healthCheck()});}catch{res.status(503).json({ok:false,error:'Database unavailable'});}});
app.use('/api/installer',installerRouter);
app.use('/api/auth',authRouter);
app.use('/api/auth',userAuthRouter);
app.use('/api',maintenanceGate);
app.use('/api',anilistRouter);
app.use('/api',episodesRouter);
app.use('/api',providersRouter);
app.use('/api',providerConsoleRouter);
app.use('/api',providerHealthRouter);
app.use('/api',publicCatalogRouter);
app.use('/api',homepageRouter);
app.use('/api',templateRouter);
app.use('/api',siteBuilderRouter);
app.use('/api',appearanceRouter);
app.use('/api',appearanceUploadRouter);
app.use('/api',navigationRouter);
app.use('/api',footerRouter);
app.use('/api',pagesRouter);
app.use('/api',seoRouter);
app.use('/api',usersRouter);
app.use('/api',communityRouter);
app.use('/api',notificationsRouter);
app.use('/api',emailRouter);
app.use('/api',auditRouter);
app.use('/api',backupsRouter);
app.use('/api',systemInfoRouter);
app.use('/api',cacheRouter);
app.use('/api',maintenanceRouter);
app.use('/api',updatesRouter);
app.use('/api',licenseRouter);
app.use('/api',supportRouter);
app.use('/api',oauthRouter);

// Process scheduled customer notifications without requiring a separate worker.
const notificationScheduler=setInterval(()=>{processDueNotifications().catch(()=>{});},60000);
notificationScheduler.unref?.();
processDueNotifications().catch(()=>{});
app.get('/api/system/install',(_req,res)=>res.json({installationId:config.installationId,domain:config.domain,nodeEnv:config.nodeEnv}));

const start=async()=>{if(await isInstallerLocked())await runMigrations();app.listen(config.port,()=>console.log('AniFuze server listening on :' + config.port));};
start().catch(error=>{console.error('AniFuze startup failed:',error.message);process.exit(1);});