import {createBrowserRouter,Navigate} from 'react-router-dom';
import {PublicLayout} from '../layouts/PublicLayout'; import {CustomerAdminLayout} from '../layouts/CustomerAdminLayout'; import {PlatformAdminLayout} from '../layouts/PlatformAdminLayout'; import {RequireCustomer,RequirePlatformAdmin} from './App';
import {HomePage,CatalogPage,AnimeDetailsPage,WatchPage,AuthPage,CustomPage} from '../pages/public/PublicPages';
import {DashboardPage,AnimeManagementPage,AnimeEditorPage,EpisodesPage,ProviderManagementPage,ProviderEditorPage,ProviderConsolePage,ProviderHealthPage,SourcesPage,MarketplacePage,TemplateDetailsPage,MyTemplatesPage,BuilderPage,AppearancePage,NavigationPage,PagesPage,ConfigPage} from '../pages/manage/ManagePages'; import {PlatformDashboard,PlatformTable} from '../pages/platform/PlatformPages';
const catalog=['browse','search','schedule','genres','latest','trending','movies','ongoing','completed','favorites','watchlist','history','continue-watching','profile'];const configs=['genres','collections','schedule','users','comments','reports','purchases','seo','domains','analytics','notifications','settings'];
const publicRoutes=[{index:true,element:<HomePage/>},...catalog.map(path=>({path,element:<CatalogPage/>})),{path:'anime/:id',element:<AnimeDetailsPage/>},{path:'watch/:id',element:<WatchPage/>},{path:'pages/:slug',element:<CustomPage/>},{path:'login',element:<AuthPage/>},{path:'register',element:<AuthPage/>}];
const manageRoutes=[{path:'manage',element:<Navigate to="/manage/dashboard" replace/>},{path:'manage/dashboard',element:<DashboardPage/>},{path:'manage/anime',element:<AnimeManagementPage/>},{path:'manage/anime/new',element:<AnimeEditorPage/>},{path:'manage/anime/:id',element:<AnimeEditorPage/>},{path:'manage/episodes',element:<EpisodesPage/>},{path:'manage/episodes/:id',element:<EpisodesPage/>},{path:'manage/providers',element:<ProviderManagementPage/>},{path:'manage/providers/new',element:<ProviderEditorPage/>},{path:'manage/providers/console',element:<ProviderConsolePage/>},{path:'manage/providers/health',element:<ProviderHealthPage/>},{path:'manage/providers/sources',element:<SourcesPage/>},{path:'manage/providers/:id',element:<ProviderEditorPage/>},{path:'manage/templates/marketplace',element:<MarketplacePage/>},{path:'manage/templates',element:<MyTemplatesPage/>},{path:'manage/templates/:id',element:<TemplateDetailsPage/>},{path:'manage/site-builder',element:<BuilderPage/>},{path:'manage/site-builder/:page',element:<BuilderPage/>},{path:'manage/appearance',element:<AppearancePage/>},{path:'manage/navigation',element:<NavigationPage/>},{path:'manage/pages',element:<PagesPage/>},...configs.map(kind=>({path:'manage/'+kind,element:<ConfigPage kind={kind}/>}))];
const platformRoutes=[{path:'platform',element:<PlatformDashboard/>},...['customers','templates','creators','orders','reviews','reports','settings'].map(kind=>({path:'platform/'+kind,element:<PlatformTable kind={kind}/>}))];
export const router=createBrowserRouter([{element:<PublicLayout/>,children:publicRoutes},{element:<RequireCustomer/>,children:[{element:<CustomerAdminLayout/>,children:manageRoutes}]},{element:<RequirePlatformAdmin/>,children:[{element:<PlatformAdminLayout/>,children:platformRoutes}]},{path:'*',element:<Navigate to="/" replace/>}],{basename:import.meta.env.BASE_URL.replace(/\/$/,'')});
