import express from 'express';
import {config,assertProductionConfig} from './config.js';
import {healthCheck} from './db/index.js';
import {runMigrations} from './migrate.js';
import {installerRouter} from './routes/installer.js';
import {authRouter} from './routes/auth.js';
import {userAuthRouter} from './routes/userAuth.js';
import {userDataRouter} from './routes/userData.js';
import {watchProgressRouter} from './routes/watchProgress.js';
import {anilistRouter} from './routes/anilist.js';
import {episodesRouter} from './routes/episodes.js';
import {providersRouter} from './routes/providers.js';
import {providerConsoleRouter} from './routes/providerConsole.js';
import {providerHealthRouter} from './routes/providerHealth.js';
import {monitorProviderHealth} from './services/providerHealth.js';
import {providerMarketplaceRouter} from './routes/providerMarketplace.js';
import {providerSdkRouter} from './routes/providerSdk.js';
import {publicCatalogRouter} from './routes/publicCatalog.js';
import {homepageRouter} from './routes/homepage.js';
import {templateRouter} from './routes/templates.js';
import {siteBuilderRouter} from './routes/siteBuilder.js';
import {appearanceRouter} from './routes/appearance.js';
import {appearanceUploadRouter} from './routes/appearanceUpload.js';
import {navigationRouter} from './routes/navigation.js';
import {footerRouter} from './routes/footer.js';
import {pagesRouter} from './routes/pages.js';
import {seoRouter} from './routes/seo.js';
import {usersRouter} from './routes/users.js';
import {communityRouter} from './routes/community.js';
import {notificationsRouter} from './routes/notifications.js';
import {emailRouter} from './routes/email.js';
import {auditRouter} from './routes/audit.js';
import {backupsRouter} from './routes/backups.js';
import {systemInfoRouter} from './routes/systemInfo.js';
import {cacheRouter} from './routes/cache.js';
import {maintenanceRouter} from './routes/maintenance.js';
import {updatesRouter} from './routes/updates.js';
import {licenseRouter} from './routes/license.js';
import {supportRouter} from './routes/support.js';
import {oauthRouter} from './routes/oauth.js';
import {siteConfigRouter} from './routes/siteConfig.js';
import {streamsRouter} from './routes/streams.js';
import {providerDiagnosticsRouter} from './routes/providerDiagnostics.js';
import {analyticsRouter} from './routes/analytics.js';
import {platformRouter} from './routes/platform.js';
import {maintenanceGate} from './services/maintenance.js';
import {processDueNotifications} from './services/notifications.js';
import {isInstallerLocked} from '../../installer/server/index.js';
import {installationGate} from './middleware/installationGate.js';
import {securityHeaders,requestId,apiRateLimit,pruneRateLimitBuckets} from './middleware/security.js';
import {releaseRouter} from './routes/release.js';

const app=express();
app.disable('x-powered-by');
app.set('trust proxy', config.nodeEnv === 'production' ? 1 : false);
app.use(requestId);
app.use(securityHeaders);
app.use(apiRateLimit);
app.use(express.json({limit:'10mb',strict:true}));
app.use('/uploads',express.static('storage/uploads',{fallthrough:false,maxAge:'1h',index:false}));

app.get('/api/health',async(_req,res)=>{try{res.json({ok:true,service:'anifuze',database:await healthCheck()});}catch{res.status(503).json({ok:false,error:'Database unavailable'});}});
app.use('/api/installer',installerRouter);
app.use(installationGate);
app.use('/api/auth',authRouter);
app.use('/api/auth',userAuthRouter);
app.use('/api',userDataRouter);
app.use('/api',watchProgressRouter);
app.use('/api',maintenanceGate);
app.use('/api',anilistRouter);
app.use('/api',episodesRouter);
app.use('/api',providersRouter);
app.use('/api',providerConsoleRouter);
app.use('/api',providerHealthRouter);
app.use('/api',providerMarketplaceRouter);
app.use('/api',providerSdkRouter);
app.use('/api',publicCatalogRouter);
app.use('/api',homepageRouter);
app.use('/api',templateRouter);
app.use('/api',siteBuilderRouter);
app.use('/api',appearanceRouter);
app.use('/api',appearanceUploadRouter);
app.use('/api',navigationRouter);
app.use('/api',footerRouter);
app.use('/api',pagesRouter);
app.use('/api',seoRouter);
app.use('/api',usersRouter);
app.use('/api',communityRouter);
app.use('/api',notificationsRouter);
app.use('/api',emailRouter);
app.use('/api',auditRouter);
app.use('/api',backupsRouter);
app.use('/api',systemInfoRouter);
app.use('/api',cacheRouter);
app.use('/api',maintenanceRouter);
app.use('/api',updatesRouter);
app.use('/api',releaseRouter);
app.use('/api',licenseRouter);
app.use('/api',supportRouter);
app.use('/api',oauthRouter);
app.use('/api',siteConfigRouter);
app.use('/api',streamsRouter);
app.use('/api',providerDiagnosticsRouter);
app.use('/api',analyticsRouter);
app.use('/api',platformRouter);

app.use((req,res,next)=>{if(req.path.startsWith('/api/'))return res.status(404).json({ok:false,error:'API route not found',requestId:req.requestId});next();});
app.use((error,req,res,next)=>{if(res.headersSent)return next(error);console.error('AniFuze request error:',error);const status=Number(error?.status)||500;res.status(status>=400&&status<600?status:500).json({ok:false,error:config.nodeEnv==='production'?'Internal server error':String(error?.message||error),requestId:req.requestId});});

const rateLimitCleanup=setInterval(pruneRateLimitBuckets,300000); rateLimitCleanup.unref?.();
const providerHealthScheduler=setInterval(()=>{monitorProviderHealth().catch(()=>{});},300000);
providerHealthScheduler.unref?.();
const notificationScheduler=setInterval(()=>{processDueNotifications().catch(()=>{});
setTimeout(()=>monitorProviderHealth().catch(()=>{}),30000).unref?.();},60000);
notificationScheduler.unref?.();
processDueNotifications().catch(()=>{});
app.get('/api/system/install',(_req,res)=>res.json({installationId:config.installationId,domain:config.domain,nodeEnv:config.nodeEnv}));

let server;
const shutdown=async(signal)=>{console.log('AniFuze shutting down ('+signal+')');for(const timer of [providerHealthScheduler,notificationScheduler,rateLimitCleanup])clearInterval(timer);if(server)await new Promise(resolve=>server.close(resolve));process.exit(0);};
process.once('SIGTERM',()=>shutdown('SIGTERM')); process.once('SIGINT',()=>shutdown('SIGINT'));
const start=async()=>{assertProductionConfig();if(await isInstallerLocked())await runMigrations();server=app.listen(config.port,()=>console.log('AniFuze server listening on :' + config.port));};
start().catch(error=>{console.error('AniFuze startup failed:',error.message);process.exit(1);});
