import crypto from 'node:crypto';
import {query} from '../db/index.js';

const id=()=>crypto.randomUUID();
function device(ua=''){const x=String(ua).toLowerCase();return /mobile|android|iphone/.test(x)?'Mobile':/tablet|ipad/.test(x)?'Tablet':'Desktop';}
function browser(ua=''){const x=String(ua);if(/Edg\//.test(x))return'Edge';if(/Chrome\//.test(x))return'Chrome';if(/Firefox\//.test(x))return'Firefox';if(/Safari\//.test(x)&&!/Chrome\//.test(x))return'Safari';return'Other';}
export async function recordAnalyticsEvent(input={},req={}){const type=String(input.event_type||input.type||'').trim().slice(0,64);if(!type)throw new Error('Analytics event type is required.');const duration=Math.max(0,Math.floor(Number(input.duration_seconds)||0));const row={id:id(),event_type:type,user_id:input.user_id?String(input.user_id):null,anime_id:input.anime_id?String(input.anime_id).slice(0,128):null,episode_id:input.episode_id?String(input.episode_id).slice(0,128):null,session_id:input.session_id?String(input.session_id).slice(0,128):null,path:input.path?String(input.path).slice(0,2000):null,referrer:input.referrer?String(input.referrer).slice(0,2000):null,device_type:device(req.headers?.['user-agent']),browser:browser(req.headers?.['user-agent']),country:null,duration_seconds:duration,created_at:new Date().toISOString()};await query('INSERT INTO af_analytics_events(id,event_type,user_id,anime_id,episode_id,session_id,path,referrer,device_type,browser,country,duration_seconds,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',Object.values(row));return row;}
export async function getAnalytics({days=7}={}){const d=Math.min(Math.max(Number(days)||7,1),90);const since=new Date(Date.now()-d*86400000).toISOString();const [totals,popular,devices,providers]=await Promise.all([
 query("SELECT event_type,COUNT(*)::int AS count,COUNT(DISTINCT COALESCE(session_id,id))::int AS sessions FROM af_analytics_events WHERE created_at >= $1 GROUP BY event_type",[since]),
 query("SELECT anime_id,COUNT(*)::int AS views FROM af_analytics_events WHERE created_at >= $1 AND event_type IN ('anime_view','stream_start') AND anime_id IS NOT NULL GROUP BY anime_id ORDER BY views DESC LIMIT 10",[since]),
 query("SELECT COALESCE(device_type,'Other') AS device_type,COUNT(*)::int AS sessions FROM af_analytics_events WHERE created_at >= $1 GROUP BY device_type ORDER BY sessions DESC",[since]),
 query("SELECT COUNT(*)::int AS requests,COALESCE(AVG(response_time_ms),0)::float AS avg_ms FROM af_provider_request_history WHERE created_at >= $1",[since])
]);const map=Object.fromEntries(totals.rows.map(x=>[x.event_type,x]));return {days:d,since,visitors:Number(map.page_view?.sessions||0),users:Number(map.user_login?.sessions||0),animeViews:Number(map.anime_view?.count||0),streamStarts:Number(map.stream_start?.count||0),events:totals.rows,popular:popular.rows,devices:devices.rows,providerPerformance:providers.rows[0]||{requests:0,avg_ms:0}};}
