import {query} from '../db/index.js';
const DEFAULT_BLOCKS=[
{id:'hero',page:'home',block_type:'Hero',title:'Eclipse Samurai',content:'A cinematic collection, curated for curious nights.',config:{},sort_order:0,visible:true},
{id:'trending',page:'home',block_type:'Anime Grid',title:'Trending now',content:'Hand-picked titles for your next watch.',config:{limit:6},sort_order:1,visible:true},
{id:'latest',page:'home',block_type:'Anime Carousel',title:'Latest episodes',content:'Fresh releases from your configured sources.',config:{limit:6},sort_order:2,visible:true},
{id:'schedule',page:'home',block_type:'Schedule',title:'Release schedule',content:'Know what is arriving next.',config:{limit:6},sort_order:3,visible:true},
{id:'cta',page:'home',block_type:'CTA',title:'Keep watching',content:'Your list is ready when you are.',config:{},sort_order:4,visible:true}
];
const parse=v=>{try{return typeof v==='string'?JSON.parse(v):v||{}}catch{return {}}};
const map=r=>r.rows.map(x=>({...x,config:parse(x.config),hidden:!Boolean(x.visible)}));
async function seed(){const c=await query('SELECT COUNT(*)::int AS count FROM af_site_builder WHERE page=$1',['home']);if(Number(c.rows[0].count)===0){for(const b of DEFAULT_BLOCKS)await query('INSERT INTO af_site_builder(id,page,block_type,title,content,config,sort_order,visible,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CURRENT_TIMESTAMP)',[b.id,b.page,b.block_type,b.title,b.content,JSON.stringify(b.config),b.sort_order,b.visible]);}}
export async function listBlocks(page='home',publicOnly=false){await seed();const r=await query('SELECT id,page,block_type,title,content,config,sort_order,visible,updated_at FROM af_site_builder WHERE page=$1 '+(publicOnly?'AND visible=TRUE ':'')+'ORDER BY sort_order ASC',[page]);return map(r);}
export async function saveBlocks(page,blocks){if(!Array.isArray(blocks)||blocks.length>100)throw new Error('Invalid builder layout.');await seed();const valid=blocks.map((b,i)=>{if(!b?.id||!b?.block_type||!b?.title)throw new Error('Each block requires an id, type, and title.');return{id:String(b.id).slice(0,128),page,block_type:String(b.block_type).slice(0,64),title:String(b.title).slice(0,255),content:String(b.content||'').slice(0,10000),config:b.config&&typeof b.config==='object'?b.config:{},sort_order:i,visible:b.visible!==false};});const existing=await query('SELECT id FROM af_site_builder WHERE page=$1',[page]);const keep=new Set(valid.map(b=>b.id));for(const row of existing.rows)if(!keep.has(row.id))await query('DELETE FROM af_site_builder WHERE id=$1',[row.id]);for(const b of valid){const found=await query('SELECT id FROM af_site_builder WHERE id=$1',[b.id]);if(found.rows.length)await query('UPDATE af_site_builder SET block_type=$1,title=$2,content=$3,config=$4,sort_order=$5,visible=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$7',[b.block_type,b.title,b.content,JSON.stringify(b.config),b.sort_order,b.visible,b.id]);else await query('INSERT INTO af_site_builder(id,page,block_type,title,content,config,sort_order,visible,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CURRENT_TIMESTAMP)',[b.id,page,b.block_type,b.title,b.content,JSON.stringify(b.config),b.sort_order,b.visible]);}return listBlocks(page);}
export {DEFAULT_BLOCKS};