CREATE TABLE IF NOT EXISTS af_email_templates (
 id VARCHAR(128) PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 subject VARCHAR(255) NOT NULL,
 html TEXT NOT NULL,
 text TEXT NOT NULL DEFAULT '',
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS af_email_settings (
 id INTEGER PRIMARY KEY,
 enabled BOOLEAN NOT NULL DEFAULT FALSE,
 host VARCHAR(255) NOT NULL DEFAULT '',
 port INTEGER NOT NULL DEFAULT 587,
 secure BOOLEAN NOT NULL DEFAULT FALSE,
 username VARCHAR(255) NOT NULL DEFAULT '',
 password TEXT NOT NULL DEFAULT '',
 from_email VARCHAR(255) NOT NULL DEFAULT '',
 from_name VARCHAR(255) NOT NULL DEFAULT 'AniFuze',
 updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS af_email_log (
 id VARCHAR(128) PRIMARY KEY,
 recipient VARCHAR(320) NOT NULL,
 template_id VARCHAR(128),
 subject VARCHAR(255) NOT NULL,
 status VARCHAR(32) NOT NULL,
 error TEXT,
 created_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS af_email_log_created_idx ON af_email_log(created_at);
