import {useEffect,useState} from 'react';
import {Button,Card,StatCard,Badge,EmptyState} from '../../components/ui';
import {useApp} from '../../contexts/AppContext';

export function AuditLogsPage(){
 const{toast}=useApp();const[items,setItems]=useState<any[]>([]);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(true);const[q,setQ]=useState('');const[action,setAction]=useState('');const[resourceType,setResourceType]=useState('');
 const load=async()=>{setLoading(true);try{const p=new URLSearchParams({limit:'100'});if(q)p.set('q',q);if(action)p.set('action',action);if(resourceType)p.set('resourceType',resourceType);const r=await fetch('/api/admin/audit-logs?'+p);const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load audit logs');setItems(d.items||[]);setTotal(d.total||0)}catch(e:any){toast(e.message,'error')}finally{setLoading(false)}};
 useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[q,action,resourceType]);
 const actions=[...new Set(items.map(x=>x.action).filter(Boolean))].sort(); const resources=[...new Set(items.map(x=>x.resource_type).filter(Boolean))].sort();
 return <><div className="page-heading"><p>Track security-sensitive administrator activity and changes made to your AniFuze installation.</p><Button variant="ghost" onClick={load} disabled={loading}>{loading?'Loading…':'Refresh'}</Button></div>
 <div className="stats"><StatCard name="Events loaded" value={String(items.length)}/><StatCard name="Total events" value={String(total)}/><StatCard name="Latest event" value={items[0]?.created_at?new Date(items[0].created_at).toLocaleDateString():'—'}/><StatCard name="Tracked fields" value="Action · Resource · Actor"/></div>
 <Card title="Audit activity"><div className="audit-filters"><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search action, resource, ID, or admin email…"/><select value={action} onChange={e=>setAction(e.target.value)}><option value="">All actions</option>{actions.map(x=><option key={x}>{x}</option>)}</select><select value={resourceType} onChange={e=>setResourceType(e.target.value)}><option value="">All resources</option>{resources.map(x=><option key={x}>{x}</option>)}</select></div>{!loading&&!items.length?<EmptyState title="No audit events found."/>:<div className="table-wrap"><table><thead><tr>{['Time','Admin','Action','Resource','Details','IP','User agent'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.created_at?new Date(x.created_at).toLocaleString():'—'}</td><td>{x.email||'System'}</td><td><Badge tone="Healthy">{x.action}</Badge></td><td>{x.resource_type?(x.resource_type+(x.resource_id?' · '+x.resource_id:'')):'—'}</td><td><code className="audit-details">{JSON.stringify(x.details||{})}</code></td><td>{x.ip_address||'—'}</td><td className="audit-agent">{x.user_agent||'—'}</td></tr>)}</tbody></table></div>}</Card></>
}