import {useEffect,useState} from 'react';
import {Button,Card,StatCard,EmptyState} from '../../components/ui';
import {useApp} from '../../contexts/AppContext';

export function BackupsPage(){
 const{toast}=useApp();const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/backups');const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load backups');setItems(d.items||[])}catch(e:any){toast(e.message,'error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const create=async()=>{setBusy('create');try{const r=await fetch('/api/admin/backups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:'manual'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Backup failed');await load();toast('Backup created successfully')}catch(e:any){toast(e.message,'error')}finally{setBusy('')}}
 const download=async(filename:string)=>{setBusy(filename);try{const r=await fetch('/api/admin/backups/'+encodeURIComponent(filename));const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not read backup');const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}catch(e:any){toast(e.message,'error')}finally{setBusy('')}}
 const restore=async(backup:any)=>{const confirmText=prompt('This replaces current AniFuze data with the selected backup. Type RESTORE to continue.');if(confirmText!=='RESTORE')return toast('Restore cancelled.','error');setBusy('restore');try{const r=await fetch('/api/admin/backups/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:'RESTORE',backup})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Restore failed');toast('Restore completed. Reloading…');setTimeout(()=>location.reload(),800)}catch(e:any){toast(e.message,'error')}finally{setBusy('')}}
 const restoreStored=async(filename:string)=>{try{const r=await fetch('/api/admin/backups/'+encodeURIComponent(filename));const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load backup');await restore(d)}catch(e:any){toast(e.message,'error')}}
 const restoreFile=(file:File)=>{const reader=new FileReader();reader.onload=async()=>{try{await restore(JSON.parse(String(reader.result||'')))}catch{toast('Invalid backup JSON.','error')}};reader.readAsText(file)};
 const remove=async(filename:string)=>{if(!confirm('Delete this backup file?'))return;setBusy(filename);try{const r=await fetch('/api/admin/backups/'+encodeURIComponent(filename),{method:'DELETE'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Delete failed');await load();toast('Backup deleted')}catch(e:any){toast(e.message,'error')}finally{setBusy('')}};
 return <><div className="page-heading"><p>Create portable database snapshots, download them to your computer, and restore an AniFuze installation when needed.</p><div className="actions"><Button variant="ghost" onClick={load} disabled={loading}>Refresh</Button><Button onClick={create} disabled={busy==='create'}>{busy==='create'?'Creating…':'Create backup'}</Button><label className="button"><input hidden type="file" accept="application/json,.json" onChange={e=>e.target.files?.[0]&&restoreFile(e.target.files[0])}/>Restore file</label></div></div>
 <div className="stats"><StatCard name="Stored backups" value={String(items.length)}/><StatCard name="Latest backup" value={items[0]?.createdAt?new Date(items[0].createdAt).toLocaleString():'—'}/><StatCard name="Storage used" value={formatBytes(items.reduce((n,x)=>n+Number(x.size||0),0))}/></div>
 <Card title={loading?'Loading backups…':String(items.length)+' stored backups'}>{!loading&&!items.length?<EmptyState title="No backups yet."/>:<div className="table-wrap"><table><thead><tr><th>Created</th><th>File</th><th>Size</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.filename}><td>{new Date(x.createdAt).toLocaleString()}</td><td><code>{x.filename}</code></td><td>{formatBytes(x.size)}</td><td><button className="link-button" disabled={busy===x.filename} onClick={()=>download(x.filename)}>Download</button> · <button className="link-button" disabled={busy==='restore'} onClick={()=>restoreStored(x.filename)}>Restore</button> · <button className="link-button danger-text" disabled={busy===x.filename} onClick={()=>remove(x.filename)}>Delete</button></td></tr>)}</tbody></table></div>}</Card>
 <Card title="Restore safety"><p className="muted">Backups contain AniFuze database tables. Restore replaces the matching <code>af_*</code> tables on this installation. Keep an offline copy before restoring and never upload an untrusted backup.</p></Card></>;
}
function formatBytes(n:number){if(!n)return '0 B';const units=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),units.length-1);return (n/Math.pow(1024,i)).toFixed(i?1:0)+' '+units[i];}
