import {useEffect,useState} from 'react';
import {Activity,Clock3,Database,HardDrive,MemoryStick,MonitorCog,RefreshCw,Server,ShieldCheck,Terminal} from 'lucide-react';

const bytes=(n:number)=>{if(!n)return '0 B';const u=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return (n/Math.pow(1024,i)).toFixed(i?1:0)+' '+u[i]};
const duration=(s:number)=>{const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return [d?d+'d':null,h? h+'h':null,m+'m'].filter(Boolean).join(' ')||'<1m'};
export function SystemInfoPage(){
 const[data,setData]=useState<any>();const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[refreshing,setRefreshing]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/system-info');const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load system information');setData(d.system)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};
 if(loading&&!data)return <div className="system-info-loading">Loading system information…</div>;
 if(error&&!data)return <div className="system-info-error"><h2>System information unavailable</h2><p>{error}</p><button onClick={load}>Retry</button></div>;
 return <section className="system-info-page">
  <div className="page-heading"><div><span className="system-kicker"><MonitorCog size={13}/> SYSTEM DIAGNOSTICS</span><p>Live runtime, database, storage, and installation information for this AniFuze instance.</p></div><button className="button" onClick={refresh} disabled={refreshing}><RefreshCw size={14} className={refreshing?'system-spin':''}/>{refreshing?'Refreshing…':'Refresh'}</button></div>
  <div className="stats"><article className="stat"><span>Environment</span><strong>{data.application.environment}</strong><small>{data.application.version}</small></article><article className="stat"><span>Database</span><strong>{data.database.ok?'Healthy':'Offline'}</strong><small>{data.database.client.toUpperCase()} · {data.database.tableCount} tables</small></article><article className="stat"><span>Uptime</span><strong>{duration(data.application.uptimeSeconds)}</strong><small>Process uptime</small></article><article className="stat"><span>Node.js</span><strong>{data.runtime.node.replace('v','')}</strong><small>{data.runtime.platform} / {data.runtime.arch}</small></article></div>
  <div className="system-grid">
   <article className="panel"><header><div><h3><Server size={15}/> Application</h3><p>Installation identity and deployment context.</p></div><ShieldCheck size={16}/></header><dl className="system-dl"><Row label="Product" value={data.application.name}/><Row label="Domain" value={data.application.domain}/><Row label="Installation ID" value={data.application.installationId}/><Row label="Environment" value={data.application.environment}/><Row label="Version" value={data.application.version}/><Row label="Generated" value={new Date(data.generatedAt).toLocaleString()}/></dl></article>
   <article className="panel"><header><div><h3><Activity size={15}/> Runtime</h3><p>Current server process resources.</p></div><Terminal size={16}/></header><dl className="system-dl"><Row label="Node.js" value={data.runtime.node}/><Row label="Platform" value={data.runtime.platform}/><Row label="Architecture" value={data.runtime.arch}/><Row label="CPU cores" value={String(data.runtime.cpus)}/><Row label="Process uptime" value={duration(data.application.uptimeSeconds)}/></dl></article>
   <article className="panel"><header><div><h3><MemoryStick size={15}/> Memory</h3><p>Host and Node process memory.</p></div><MemoryStick size={16}/></header><dl className="system-dl"><Row label="System total" value={bytes(data.runtime.memory.total)}/><Row label="System free" value={bytes(data.runtime.memory.free)}/><Row label="Heap total" value={bytes(data.runtime.memory.heapTotal)}/><Row label="Heap used" value={bytes(data.runtime.memory.heapUsed)}/></dl></article>
   <article className="panel"><header><div><h3><HardDrive size={15}/> Storage</h3><p>Filesystem capacity available to the server.</p></div><HardDrive size={16}/></header>{data.storage?<dl className="system-dl"><Row label="Total" value={bytes(data.storage.total)}/><Row label="Used" value={bytes(data.storage.used)}/><Row label="Free" value={bytes(data.storage.free)}/><Row label="Usage" value={((data.storage.used/data.storage.total)*100).toFixed(1)+'%'}/></dl>:<p className="muted">Filesystem statistics unavailable.</p>}</article>
   <article className="panel"><header><div><h3><Database size={15}/> Database</h3><p>Connection health and AniFuze schema.</p></div><span className={data.database.ok?'system-health good':'system-health bad'}>{data.database.ok?'HEALTHY':'OFFLINE'}</span></header><dl className="system-dl"><Row label="Engine" value={data.database.client.toUpperCase()}/><Row label="Connection" value={data.database.ok?'Connected':'Unavailable'}/><Row label="AniFuze tables" value={String(data.database.tableCount)}/>{data.database.error&&<Row label="Error" value={data.database.error}/>}</dl></article>
   <article className="panel"><header><div><h3><Clock3 size={15}/> Diagnostics</h3><p>Quick checks useful before maintenance or updates.</p></div><Clock3 size={16}/></header><ul className="system-checks"><li><i className={data.database.ok?'ok':''}/><span>Database connectivity</span><b>{data.database.ok?'PASS':'FAIL'}</b></li><li><i className="ok"/><span>Node runtime detected</span><b>PASS</b></li><li><i className="ok"/><span>Installation identity configured</span><b>PASS</b></li></ul></article>
  </div>
 </section>;
}
function Row({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd title={value}>{value}</dd></div>}
