import {useEffect,useState} from 'react';
import {Button,Card} from '../../components/ui';
import {useApp} from '../../contexts/AppContext';

export function UsersPage(){
 const{toast}=useApp();const[users,setUsers]=useState<any[]>([]);const[q,setQ]=useState('');const[status,setStatus]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState('');
 const load=async()=>{setLoading(true);try{const p=new URLSearchParams();if(q)p.set('q',q);if(status)p.set('status',status);const r=await fetch('/api/admin/users?'+p);const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load users');setUsers(d.users||[])}catch(e:any){toast(e.message,'error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[status]);
 const patch=async(id:string,body:any)=>{setSaving(id);try{const r=await fetch('/api/admin/users/'+encodeURIComponent(id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not update user');setUsers(x=>x.map(u=>u.id===id?d.user:u));toast('User updated')}catch(e:any){toast(e.message,'error')}finally{setSaving('')}};
 const remove=async(id:string)=>{if(!window.confirm('Delete this user and their stored account activity?'))return;setSaving(id);try{const r=await fetch('/api/admin/users/'+encodeURIComponent(id),{method:'DELETE'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not delete user');setUsers(x=>x.filter(u=>u.id!==id));toast('User deleted')}catch(e:any){toast(e.message,'error')}finally{setSaving('')}};
 return <section className="form-page"><div className="page-heading"><div><h1>Users</h1><p>Manage customer accounts, status, profile identifiers, and passwords.</p></div><Button onClick={load}>Refresh</Button></div>
  <Card title="Customer accounts"><div className="form-grid"><label>Search<input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Username, email, or ID"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label></div>
   {loading?<p>Loading users…</p>:<div className="table-wrap"><table><thead><tr><th>Username</th><th>Email</th><th>Status</th><th>Created</th><th>Last active</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.email}</td><td><select value={u.status} disabled={saving===u.id} onChange={e=>patch(u.id,{status:e.target.value})}><option value="active">Active</option><option value="disabled">Disabled</option></select></td><td>{new Date(u.created_at).toLocaleString()}</td><td>{u.last_active_at?new Date(u.last_active_at).toLocaleString():'Never'}</td><td><Button disabled={saving===u.id} onClick={()=>{const email=window.prompt('Email',u.email);if(email!==null)patch(u.id,{email})}}>Edit email</Button> <Button disabled={saving===u.id} onClick={()=>{const password=window.prompt('New password (12+ characters)');if(password)fetch('/api/admin/users/'+encodeURIComponent(u.id)+'/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}).then(r=>r.json()).then(d=>{if(!d.ok)throw new Error(d.error||'Could not reset password');toast('Password reset')}).catch(e=>toast(e.message,'error'))}}>Reset password</Button> <Button disabled={saving===u.id} onClick={()=>remove(u.id)}>Delete</Button></td></tr>)}</tbody></table></div>}
  </Card>
 </section>;
}