import {useEffect,useMemo,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Award,Check,Clock,Edit3,Heart,Play,Sparkles,Tv,UserRound,LogOut,Server} from 'lucide-react';
import {useApp} from '../../contexts/AppContext';
import {watchProgressService} from '../../services/watchProgressService';
import {fetchAnimeById} from '../../services/anilistService';
type WatchItem={animeId:string;episode:number;progressSeconds:number;durationSeconds:number;updatedAt:number};
type Tab='continue'|'favorites'|'history'|'recommendations';
const formatTime=(seconds:number)=>{const m=Math.floor(seconds/60);return m+':'+String(Math.floor(seconds%60)).padStart(2,'0')};
export function ProfilePage(){
 const{customerUser,logoutCustomer,toast}=useApp();const navigate=useNavigate();
 const[profile,setProfile]=useState<any>(null),[tab,setTab]=useState<Tab>('continue'),[history,setHistory]=useState<WatchItem[]>([]),[favorites,setFavorites]=useState<string[]>([]),[watchlist,setWatchlist]=useState<string[]>([]),[anime,setAnime]=useState<Record<string,any>>({});
 const[editing,setEditing]=useState(false),[draft,setDraft]=useState({displayName:'',bio:'',avatar:'',banner:''}),[busy,setBusy]=useState(false);
 const load=async()=>{const [p,h,f,w]=await Promise.all([fetch('/api/user/profile',{credentials:'include'}),fetch('/api/watch/history',{credentials:'include'}),fetch('/api/user/favorites',{credentials:'include'}),fetch('/api/user/watchlist',{credentials:'include'})]);if(!p.ok||!h.ok||!f.ok||!w.ok)throw new Error('Could not load your account.');const pd=await p.json(),hd=await h.json(),fd=await f.json(),wd=await w.json();setProfile(pd.profile);setDraft({displayName:pd.profile.displayName,bio:pd.profile.bio||'',avatar:pd.profile.avatar||'',banner:pd.profile.banner||''});setHistory((hd.history||[]).map((x:any)=>({animeId:String(x.anime_id),episode:Number(x.episode_id)||1,progressSeconds:Number(x.progress_seconds)||0,durationSeconds:1440,updatedAt:new Date(x.watched_at).getTime()})));setFavorites((fd.items||[]).map((x:any)=>String(x.anime_id)));setWatchlist((wd.items||[]).map((x:any)=>String(x.anime_id)))};
 useEffect(()=>{load().catch(()=>{})},[]);
 useEffect(()=>{const ids=[...new Set([...history.map(x=>x.animeId),...favorites,...watchlist])];Promise.all(ids.slice(0,50).map(id=>fetchAnimeById(id).then(a=>[id,a] as const).catch(()=>null))).then(x=>setAnime(Object.fromEntries(x.filter(Boolean) as [string,any][])))},[history,favorites,watchlist]);
 const saveProfile=async()=>{setBusy(true);try{const r=await fetch('/api/user/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(draft)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save profile.');setProfile(d.profile);setEditing(false);toast('Profile saved.')}catch(e){toast(e instanceof Error?e.message:'Could not save profile.','error')}finally{setBusy(false)}};
 const clearHistory=async()=>{if(!confirm('Clear your entire watch history?'))return;const r=await fetch('/api/watch/history',{method:'DELETE',credentials:'include'});if(r.ok){setHistory([]);toast('Watch history cleared.')}};
 const logout=async()=>{await logoutCustomer();navigate('/login',{replace:true})};
 const continueItems=history.filter(x=>x.progressSeconds>0);const favoriteAnime=useMemo(()=>favorites.map(id=>anime[id]).filter(Boolean),[favorites,anime]);const shown=tab==='continue'?continueItems:tab==='history'?history:[];
 if(!customerUser)return null;
 const displayName=profile?.displayName||customerUser.displayName,avatar=profile?.avatar||'',banner=profile?.banner||'';
 return <section className="profile-vault"><div className="profile-vault-hero">{banner?<img src={banner} alt="" />:<div className="profile-vault-gradient"/>}<div className="profile-vault-hero-overlay"/></div><div className="profile-vault-body">
  <div className="profile-vault-head"><div className="profile-avatar">{avatar?<img src={avatar} alt={displayName}/>:<UserRound size={58}/>}</div><div className="profile-identity"><div className="profile-name-row"><h1>{displayName}</h1><span className="profile-badge"><Check size={12}/> MEMBER</span></div><p>{profile?.bio||'Anime enthusiast.'}</p><div className="profile-mini-meta"><span><Tv size={14}/> {history.length} episodes</span><span><Heart size={14}/> {favorites.length} favorites</span><span><Award size={14}/> {customerUser.email}</span></div></div><div className="vault-actions"><button className="profile-edit-btn" onClick={()=>setEditing(v=>!v)}><Edit3 size={15}/>{editing?'Cancel':'Edit Profile'}</button><Link className="profile-edit-btn" to="/providers"><Server size={15}/> Stream providers</Link><button className="profile-edit-btn" onClick={logout}><LogOut size={15}/> Sign out</button></div></div>
  {editing&&<div className="profile-editor"><label>Display name<input value={draft.displayName} maxLength={80} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></label><label>Avatar URL<input value={draft.avatar} placeholder="https://..." onChange={e=>setDraft({...draft,avatar:e.target.value})}/></label><label>Banner URL<input value={draft.banner} placeholder="https://..." onChange={e=>setDraft({...draft,banner:e.target.value})}/></label><label className="profile-editor-wide">Bio<textarea maxLength={180} value={draft.bio} onChange={e=>setDraft({...draft,bio:e.target.value})}/></label><button className="vault-primary" disabled={busy} onClick={saveProfile}><Check size={15}/> {busy?'Saving…':'Save profile'}</button></div>}
  <div className="profile-stat-grid"><div><b>{history.length}</b><span>Episodes Watched</span></div><div><b>{continueItems.length}</b><span>In Progress</span></div><div><b>{favorites.length}</b><span>Favorites</span></div><div><b>{Math.round(history.reduce((n,x)=>n+x.progressSeconds,0)/60)}</b><span>Minutes Watched</span></div></div>
  <div className="profile-tabs"><button className={tab==='continue'?'active':''} onClick={()=>setTab('continue')}><Play size={15}/> Continue ({continueItems.length})</button><button className={tab==='favorites'?'active':''} onClick={()=>setTab('favorites')}><Heart size={15}/> Favorites ({favorites.length})</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><Clock size={15}/> History ({history.length})</button><button className={tab==='recommendations'?'active':''} onClick={()=>setTab('recommendations')}><Sparkles size={15}/> For You</button></div>
  {tab==='recommendations'?<div className="profile-empty"><Sparkles size={38}/><h3>Recommendations</h3><p>Discover trending anime and build your history to personalize this space.</p><Link className="vault-secondary" to="/trending">Explore trending</Link></div>:tab==='favorites'?<div className="profile-poster-grid">{favoriteAnime.map(a=><Link className="profile-poster" to={'/anime/'+a.id} key={a.id}><img src={a.cover} alt={a.title}/><strong>{a.title}</strong></Link>)}{!favoriteAnime.length&&<div className="profile-empty"><Heart size={38}/><h3>No favorites yet</h3><Link className="vault-secondary" to="/browse">Browse anime</Link></div>}</div>:<div className="profile-watch-list">{shown.map(x=>{const a=anime[x.animeId],pct=x.durationSeconds?Math.min(100,Math.round(x.progressSeconds/x.durationSeconds*100)):0;return <div className="profile-watch-row" key={x.animeId+'-'+x.episode}><img src={a?.cover} alt=""/><div className="profile-watch-copy"><strong>{a?.title||'Loading anime…'}</strong><span>Episode {x.episode} · {formatTime(x.progressSeconds)} watched</span><div className="profile-progress"><i style={{width:pct+'%'}}/></div></div><span className="profile-percent">{pct}%</span><Link className="vault-secondary" to={'/watch/'+x.animeId+'?episode='+x.episode}>Resume</Link></div>})}{tab==='history'&&shown.length>0&&<div className="profile-history-actions"><button className="profile-danger-btn" onClick={clearHistory}>Clear watch history</button></div>}{!shown.length&&<div className="profile-empty"><Tv size={38}/><h3>{tab==='continue'?'Nothing to continue':'No watch history'}</h3><p>Start watching anime and your activity will appear here.</p><Link className="vault-primary" to="/browse">Browse anime</Link></div>}</div>}
 </div></section>;
}