import {useEffect,useState} from 'react';
import {Button,Card,Badge} from '../../components/ui';
type Provider={id?:string;name:string;type:'API'|'Embed';base_url?:string;priority:number;enabled:boolean;config_json?:any};
export function ProviderSettingsPage(){
 const [items,setItems]=useState<Provider[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [editing,setEditing]=useState<Provider|null>(null);const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/customer/providers',{credentials:'include'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load providers');setItems(d.items||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const save=async()=>{if(!editing)return;setSaving(true);setError('');try{let config=editing.config_json||{};if(typeof config==='string')config=JSON.parse(config||'{}');const r=await fetch('/api/customer/providers'+(editing.id?'/'+encodeURIComponent(editing.id):''),{method:editing.id?'PATCH':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:editing.name,type:editing.type,base_url:editing.base_url||'',priority:Number(editing.priority)||1,enabled:Boolean(editing.enabled),config})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save provider');setEditing(null);await load()}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 const remove=async(id:string)=>{if(!confirm('Remove this provider from your AniFuze installation?'))return;const r=await fetch('/api/customer/providers/'+encodeURIComponent(id),{method:'DELETE',credentials:'include'});const d=await r.json();if(!r.ok)return setError(d.error||'Unable to remove provider');await load()};
 return <section className="form-page"><div className="page-heading"><p>Configure the API and Embed stream sources included with your licensed AniFuze installation. AniFuze administrators cannot edit or remove these customer-owned stream providers.</p><div className="actions"><Button variant="ghost" onClick={load}>Refresh</Button><Button onClick={()=>setEditing({name:'',type:'API',base_url:'',priority:1,enabled:true})}>+ Add provider</Button></div></div>{error&&<Card title="Provider configuration error"><p>{error}</p></Card>}{editing&&<Card title={editing.id?'Edit stream provider':'Add stream provider'}><div className="form-grid"><label>Name<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Type<select value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value as 'API'|'Embed'})}><option>API</option><option>Embed</option></select></label><label>Base URL<input value={editing.base_url||''} onChange={e=>setEditing({...editing,base_url:e.target.value})}/></label><label>Priority<input type="number" min="1" max="999" value={editing.priority} onChange={e=>setEditing({...editing,priority:Number(e.target.value)})}/></label><label>Enabled<select value={editing.enabled?'true':'false'} onChange={e=>setEditing({...editing,enabled:e.target.value==='true'})}><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label className="wide">Configuration JSON<textarea value={typeof editing.config_json==='string'?editing.config_json:JSON.stringify(editing.config_json||{},null,2)} onChange={e=>setEditing({...editing,config_json:e.target.value})}/></label></div><div className="actions"><Button variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button><Button onClick={save} disabled={saving}>{saving?'Saving…':'Save provider'}</Button></div></Card>}<Card title={loading?'Loading stream providers…':String(items.length)+' customer stream providers'}><div className="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Status</th><th>Priority</th><th>Enabled</th><th>Actions</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.type}</td><td><Badge tone={p.status}>{p.status}</Badge></td><td>{p.priority}</td><td>{p.enabled?'Yes':'No'}</td><td><button className="link-button" onClick={()=>setEditing({...p,config_json:p.config_json||{}})}>Edit</button> · <button className="link-button danger" onClick={()=>remove(p.id!)}>Remove</button></td></tr>)}</tbody></table></div></Card></section>;
}
