import {Link,useParams,useLocation,useNavigate} from 'react-router-dom';
import {useEffect,useMemo,useState} from 'react';
import {providers} from '../../data/mock';
import {builderService} from '../../services/mockServices';
import {fetchRealHomepageAnime,fetchBrowseAnime,fetchLatestAnime,fetchAnimeSchedule,fetchAnimeById} from '../../services/anilistService';
import {useApp} from '../../contexts/AppContext';

const Card=({a,compact=false}:{a:any;compact?:boolean})=><Link className={compact?'vault-card compact':'vault-card'} to={'/anime/'+a.id}><div className="vault-card-poster"><img src={a.cover} alt={a.title}/><span className="vault-card-badge">{a.status}</span><span className="vault-card-play">▶</span></div><div className="vault-card-info"><strong>{a.title}</strong><small>{a.type} · {a.episodes} Episodes</small></div></Link>;

export function HomePage(){
 const{settings}=useApp(); const[fresh,setFresh]=useState<{trending:any[];latest:any[]}>({trending:[],latest:[]});
 useEffect(()=>{let alive=true;fetchRealHomepageAnime().then(data=>{if(alive)setFresh(data)}).catch(()=>{});return()=>{alive=false}},[]);
 const liveTrending=fresh.trending; const liveLatest=fresh.latest; const featured=liveTrending[0]; const slides=liveTrending.slice(0,5); const blocks=builderService.get().filter(b=>!b.hidden);
 return <section className="vault-home">
  <div className="vault-hero"><div className="vault-hero-bg" style={{backgroundImage:`linear-gradient(90deg,rgba(8,8,8,.98) 0%,rgba(8,8,8,.78) 38%,rgba(8,8,8,.25) 72%,rgba(8,8,8,.82) 100%),linear-gradient(0deg,#080808 0%,transparent 35%),url(${featured.banner||featured.cover})`}}/>
   <div className="vault-hero-content"><span className="vault-kicker">✦ FEATURED ANIME</span><h1>{featured.title}</h1><div className="vault-meta"><span>{featured.type}</span><i>•</i><span>{featured.status}</span><i>•</i><span>{featured.episodes||'?'} Episodes</span><i>•</i><b>★ {(featured.score||8.8).toFixed(1)}</b></div><p>{featured.description}</p><div className="vault-actions"><Link className="vault-primary" to={'/watch/'+featured.id}>▶ Watch Now</Link><Link className="vault-secondary" to={'/anime/'+featured.id}>ⓘ Details</Link></div></div>
   <div className="vault-dots">{slides.map((x,i)=><span className={i===0?'active':''} key={x.id}/>)}</div>
  </div>
  <div className="vault-container">{blocks.length?blocks.map((b:any)=><BuilderSection key={b.id} block={b} liveAnime={liveTrending} latestAnime={liveLatest}/>):<><Shelf title="Trending Anime" subtitle="What everyone is watching right now." items={liveTrending.slice(0,6)}/><Shelf title="Latest Episodes" subtitle="Fresh releases from AniList." items={liveLatest.slice(0,6)} episode/></>}
  <div className="vault-cta"><div><span>ANIFUZE</span><h2>{settings.tagline}</h2><p>Build and run your own anime streaming experience.</p></div><Link className="vault-secondary" to="/manage">Open Admin Panel ↗</Link></div></div>
 </section>;
}
function BuilderSection({block,liveAnime,latestAnime}:{block:any;liveAnime:any[];latestAnime:any[]}){const t=String(block.type||'').toLowerCase();if(t==='hero')return <div className="vault-builder-section vault-builder-hero"><span className="vault-kicker">CUSTOM HERO</span><h2>{block.title}</h2><p>{block.content}</p><Link className="vault-primary" to="/browse">Browse anime</Link></div>;if(['anime grid','anime carousel','anime card','collection','stats'].includes(t))return <Shelf title={block.title} subtitle={block.content} items={liveAnime.slice(0,6)} episode={t==='anime card'}/>;if(t==='episode list'||t==='schedule')return <Shelf title={block.title} subtitle={block.content} items={latestAnime.slice(0,6)} episode/>;if(t==='cta'||t==='banner')return <div className="vault-cta"><div><span>ANIFUZE</span><h2>{block.title}</h2><p>{block.content}</p></div><Link className="vault-secondary" to="/browse">Explore library ↗</Link></div>;if(t==='navbar'||t==='footer')return null;return <section className="vault-builder-text"><span className="vault-kicker">{block.type}</span><h2>{block.title}</h2><p>{block.content}</p></section>} 

function Shelf({title,subtitle,items,episode=false}:{title:string;subtitle:string;items:any[];episode?:boolean}){return <section className="vault-shelf"><div className="vault-section-head"><div><h2>{title}</h2><p>{subtitle}</p></div><Link to={episode?'/latest':'/trending'}>View all ›</Link></div><div className="vault-card-grid">{items.map(a=><Card a={a} key={a.id}/>)}</div></section>}

export function CatalogPage(){
 const loc=useLocation(); const[q,setQ]=useState(''); const path=loc.pathname;
 const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 const title=path==='/search'?'Search Anime':path==='/genres'?'Genres':path==='/latest'?'Latest Episodes':path==='/trending'?'Trending Anime':path==='/movies'?'Movies':path==='/ongoing'?'Ongoing Anime':path==='/completed'?'Completed Anime':path==='/favorites'?'Your Favorites':path==='/watchlist'?'Your Watchlist':path==='/history'?'Watch History':path==='/continue-watching'?'Continue Watching':'Browse Anime';
 useEffect(()=>{if(path==='/schedule')return;let alive=true;setLoading(true);const load=path==='/latest'?fetchLatestAnime():fetchBrowseAnime();load.then(x=>{if(alive)setItems(x)}).catch(()=>{if(alive)setItems([])}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[path]);
 const filtered=useMemo(()=>items.filter(a=>a.title.toLowerCase().includes(q.toLowerCase())||a.genre.toLowerCase().includes(q.toLowerCase())),[items,q]);
 if(path==='/schedule') return <SchedulePage/>;
 return <section className="vault-page"><div className="vault-page-head"><div><span className="vault-kicker">DISCOVER</span><h1>{title}</h1><p>{path==='/latest'?'Freshly updated anime from AniList.':'Explore real anime data from AniList and find your next series.'}</p></div></div>
 {path==='/search'&&<div className="vault-search"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search anime, genres, studios..."/><kbd>⌘ K</kbd></div>}
 {path==='/genres'?<div className="vault-genre-grid">{['Action','Adventure','Comedy','Drama','Fantasy','Mystery','Romance','Sci-Fi','Sports','Supernatural','Thriller','Slice of Life'].map(g=><Link to="/browse" key={g}><span>GENRE</span><strong>{g}</strong><b>→</b></Link>)}</div>:<><div className="vault-filter-row"><button className="active">All</button><button>Series</button><button>Movies</button><button>Ongoing</button><button>Completed</button></div>{loading?<div className="vault-builder-text"><h2>Loading AniList…</h2><p>Fetching the latest catalog.</p></div>:<div className="vault-library-grid">{filtered.map(a=><Card a={a} key={a.id}/>)}</div>}</>}
 </section>;
}

function SchedulePage(){
 const [items,setItems]=useState<any[]>([]);
 useEffect(()=>{let alive=true;fetchAnimeSchedule().then(x=>{if(alive)setItems(x)}).catch(()=>{if(alive)setItems([])});return()=>{alive=false}},[]);
 const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
 const grouped=days.map((d,i)=>({d,items:items.filter((x:any)=>new Date(x.airingAt*1000).getDay()===((i+1)%7))}));
 const upcoming=items[0];
 return <section className="vault-page schedule-vault"><div className="vault-page-head"><div><span className="vault-kicker">AIRING CALENDAR · ANILIST</span><h1>Anime Schedule</h1><p>Live upcoming releases from AniList.</p></div></div><div className="schedule-layout"><main>{upcoming&&<div className="schedule-feature"><img src={upcoming.banner||upcoming.cover} alt={upcoming.title}/><div><span className="vault-kicker">UP NEXT</span><h2>{upcoming.title}</h2><p>Episode {upcoming.episode} airs {new Date(upcoming.airingAt*1000).toLocaleString()}.</p><div className="countdown"><b>{String(Math.floor(upcoming.timeUntilAiring/3600)).padStart(2,'0')}</b><b>{String(Math.floor(upcoming.timeUntilAiring/60)%60).padStart(2,'0')}</b><b>{String(upcoming.timeUntilAiring%60).padStart(2,'0')}</b></div><Link className="vault-primary" to={'/anime/'+upcoming.id}>View anime</Link></div></div>}<div className="day-tabs">{days.map((d,i)=><button className={i===0?'active':''} key={d}>{d}<small>{grouped[i].items.length}</small></button>)}</div><div className="schedule-grid">{items.map(a=><Link className="schedule-card" to={'/anime/'+a.id} key={a.id+'-'+a.episode}><img src={a.cover} alt={a.title}/><div><small>{new Date(a.airingAt*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small><strong>{a.title}</strong><span>Episode {a.episode} · {a.genre}</span></div></Link>)}</div></main><aside className="schedule-side"><h3>Release activity</h3>{items.slice(0,8).map((a:any,i:number)=><div className="activity-item" key={a.id+'-side-'+i}><img src={a.cover} alt=""/><div><strong>{a.title}</strong><span>Episode {a.episode} upcoming</span></div><small>{Math.max(0,Math.floor(a.timeUntilAiring/3600))}h</small></div>)}</aside></div></section>
}
export function AnimeDetailsPage(){
 const{id}=useParams(); const[a,setA]=useState<any>(null); const[watchlist,setWatchlist]=useState(false);
 useEffect(()=>{let alive=true;if(id)fetchAnimeById(id).then(x=>{if(alive)setA(x)}).catch(()=>{});return()=>{alive=false}},[id]);
 if(!a)return <section className="vault-page"><h1>Loading anime…</h1></section>;
 const toggle=()=>{const s=JSON.parse(localStorage.getItem('anifuze_user_state')||'{}');const l=Array.isArray(s.watchlist)?s.watchlist:[];const next=watchlist?l.filter((x:string)=>x!==a.id):[...l,a.id];localStorage.setItem('anifuze_user_state',JSON.stringify({...s,watchlist:next}));setWatchlist(!watchlist)};
 return <section className="vault-detail"><div className="vault-detail-bg" style={{backgroundImage:`linear-gradient(90deg,#080808 15%,rgba(8,8,8,.78) 55%,#080808),url(${a.banner||a.cover})`}}/><div className="vault-detail-inner"><img className="vault-detail-poster" src={a.cover} alt={a.title}/><div className="vault-detail-copy"><span className="vault-kicker">{a.type} · {a.status}</span><h1>{a.title}</h1><div className="vault-meta"><span>{a.year||'—'}</span><i>•</i><span>{a.episodes||'?'} Episodes</span><i>•</i><b>★ {(a.score||0).toFixed(1)}</b></div><p>{a.description}</p><div className="vault-chip-row">{a.genre.split(' · ').map((g:string)=><span key={g}>{g}</span>)}<span>1080p</span><span>Sub</span></div><div className="vault-actions"><Link className="vault-primary" to={'/watch/'+a.id}>▶ Watch Now</Link><button className="vault-secondary" onClick={toggle}>{watchlist?'✓ In Watchlist':'+ Watchlist'}</button></div></div></div><div className="vault-episodes"><div className="vault-section-head"><div><h2>Episodes</h2><p>{a.episodes||0} episodes available</p></div></div><div className="episode-grid">{Array.from({length:Math.min(a.episodes||0,24)},(_,i)=><Link to={'/watch/'+a.id+'?episode='+(i+1)} key={i}><b>{String(i+1).padStart(2,'0')}</b><span>Episode {i+1}</span><small>24m · 1080p</small></Link>)}</div></div></section>;
}

export function WatchPage(){
 const{id}=useParams(); const a=useApp(); const[animeData,setAnimeData]=useState<any>(null); const[ep,setEp]=useState(1);
 useEffect(()=>{let alive=true;if(id)fetchAnimeById(id).then(x=>{if(alive)setAnimeData(x)}).catch(()=>{});return()=>{alive=false}},[id]);
 const save=()=>{if(!animeData)return;const s=JSON.parse(localStorage.getItem('anifuze_user_state')||'{}');localStorage.setItem('anifuze_user_state',JSON.stringify({...s,history:[animeData.id,...(s.history||[]).filter((x:string)=>x!==animeData.id)].slice(0,20)}))};
 if(!animeData)return <section className="vault-page"><h1>Loading anime…</h1></section>;
 return <section className="vault-watch"><div className="vault-player"><span>SAFE MOCK PLAYBACK</span><button onClick={save}>▶</button><small>Mock source · 1080p · Sub</small></div><div className="vault-watch-head"><div><span className="vault-kicker">NOW PLAYING</span><h1>{animeData.title}</h1><p>Episode {ep} · {animeData.genre} · Mock stream</p></div><div className="vault-actions"><button className="vault-secondary" disabled={ep===1} onClick={()=>{setEp(ep-1);save()}}>← Previous</button><button className="vault-primary" disabled={ep>=(animeData.episodes||1)} onClick={()=>{setEp(ep+1);save()}}>Next Episode →</button></div></div><div className="source-row"><span><i/> Mock source · Available</span></div><div className="watch-episodes"><h2>Episodes</h2><div className="episode-grid">{Array.from({length:Math.min(animeData.episodes||0,12)},(_,i)=><button className={ep===i+1?'current':''} onClick={()=>setEp(i+1)} key={i}>{i+1}</button>)}</div></div></section>;
}

export function AuthPage(){const{setRole}=useApp();const nav=useNavigate();const enter=(role:'customer'|'platform_admin',to:string)=>{setRole(role);nav(to)};return <section className="vault-auth"><div className="vault-auth-card"><span className="vault-kicker">ANIFUZE ACCOUNT</span><h1>Welcome back.</h1><p>Choose a safe mock role to explore the AniFuze platform.</p><button className="vault-primary" onClick={()=>enter('customer','/manage/dashboard')}>Sign in as customer</button><button className="vault-secondary" onClick={()=>enter('platform_admin','/platform')}>Sign in as platform admin</button><Link to="/">Continue as visitor</Link></div></section>}
export function CustomPage(){const{settings}=useApp();return <section className="vault-page"><span className="vault-kicker">CUSTOM PAGE</span><h1>Created with AniFuze.</h1><p>Customer-managed pages inherit the active {settings.siteName} visual system.</p></section>}
