import {Link,useParams,useLocation} from 'react-router-dom';import {useState} from 'react';import {anime} from '../../data/mock';import {useApp} from '../../contexts/AppContext';
const Card=({a}:{a:any})=><Link className="anime-card" to={'/anime/'+a.id}><img src={a.cover} alt=""/><div><span>{a.genre}</span><strong>{a.title}</strong><small>{a.episodes} episodes · {a.status}</small></div></Link>;
export function HomePage(){const{settings}=useApp();const blocks=JSON.parse(localStorage.getItem('anifuze_builder')||'[]');const hero=blocks.find((x:any)=>x.type==='Hero');return <><section className="hero"><div><span className="eyebrow">CURATED ANIMATION</span><h1>{hero?.title||'Eclipse Samurai'}</h1><p>{hero?.content||settings.tagline}</p><div className="actions"><Link className="button" to="/anime/eclipse-samurai">Start watching →</Link><Link className="button ghost" to="/browse">Explore library</Link></div></div><div className="hero-art"/></section><Shelf title={blocks.find((x:any)=>x.type==='Anime Grid')?.title||'Trending now'}/><section className="callout"><span>YOUR NEXT EPISODE IS READY</span><h2>Built for unhurried nights.</h2><Link className="button" to="/continue-watching">Continue watching</Link></section></>}
export function Shelf({title}:{title:string}){return <section className="shelf"><div className="section-title"><div><span className="eyebrow">DISCOVER</span><h2>{title}</h2></div><Link to="/browse">View all →</Link></div><div className="poster-grid">{anime.map(a=><Card a={a} key={a.id}/>)}</div></section>}
export function CatalogPage(){const loc=useLocation();const [q,setQ]=useState('');const title=loc.pathname==='/search'?'Search library':loc.pathname==='/genres'?'Genres':'Browse library';const filtered=anime.filter(a=>a.title.toLowerCase().includes(q.toLowerCase())||a.genre.toLowerCase().includes(q.toLowerCase()));return <section className="page"><span className="eyebrow">LIBRARY</span><h1>{title}</h1>{loc.pathname==='/search'&&<input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search anime, genres, studios…" autoFocus/>}<div className="filters"><button className="selected">All titles</button><button>Series</button><button>Movies</button><button>Ongoing</button></div>{title==='Genres'?<div className="chips">{['Action','Fantasy','Sci-fi','Romance','Adventure','Mystery'].map(x=><span key={x}>{x}</span>)}</div>:<div className="poster-grid">{filtered.concat(filtered).map((a,i)=><Card key={a.id+i} a={{...a,id:i?a.id+'-'+i:a.id}}/>)}</div>}</section>}
export function AnimeDetailsPage(){const{id='eclipse-samurai'}=useParams();const a=anime.find(x=>x.id===id)||anime[0];const[watchlist,setWatchlist]=useState(false);return <section className="detail"><img className="detail-cover" src={a.cover} alt=""/><div><span className="eyebrow">{a.type} · {a.status}</span><h1>{a.title}</h1><p>{a.description}</p><div className="chips"><span>{a.genre}</span><span>★ 4.8</span><span>2026</span></div><div className="actions"><Link className="button" to={'/watch/'+a.id}>Watch now →</Link><button className="button ghost" onClick={()=>setWatchlist(!watchlist)}>{watchlist?'✓ In watchlist':'+ Watchlist'}</button></div><h3>Episodes</h3><div className="episode-list">{Array.from({length:Math.min(a.episodes,10)},(_,i)=><Link key={i} to={'/watch/'+a.id}>Episode {i+1}<span>24m</span></Link>)}</div></div></section>}
export function WatchPage(){const{id}=useParams();const[ep,setEp]=useState(1);return <section className="watch"><div className="player"><span>MOCK PLAYBACK · SAFE STREAM</span><b>▶</b><small>Provider: StreamForge API · 1080p</small></div><div className="watch-info"><span className="eyebrow">NOW PLAYING</span><h1>{anime.find(x=>x.id===id)?.title||'Eclipse Samurai'} · Episode {ep}</h1><div className="actions"><button className="button ghost" disabled={ep===1} onClick={()=>setEp(ep-1)}>← Previous</button><button className="button" onClick={()=>setEp(ep+1)}>Next episode →</button></div></div></section>}
export function AuthPage(){const{setRole}=useApp();return <section className="auth"><span className="eyebrow">ANIFUZE DEMO ACCESS</span><h1>Enter your workspace.</h1><p>Choose a mock role. Private navigation is only visible after sign-in.</p><button className="button" onClick={()=>setRole('customer')}>Sign in as customer</button><button className="button ghost" onClick={()=>setRole('platform_admin')}>Sign in as platform admin</button><Link to="/">Return to public site</Link></section>}
export function CustomPage(){return <section className="page"><span className="eyebrow">CUSTOM PAGE</span><h1>Created with AniFuze.</h1><p>Customer-managed page content appears here, using the active public site styling.</p></section>}
